name: docker
on: push
jobs:
  build:
    name: build and then push if necessary
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: |-
          for image in "selenium-chrome-ruby" ; do
            docker build -t gong023/$image:latest $image
          done
      - name: Push image
        if: github.ref == 'main'
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |-
          docker login -u=gong023 -p="$DOCKER_TOKEN"
          for image in "selenium-chrome-ruby" ; do
            docker push gong023/$image:latest
          done
